// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjiynpknashtwsechbdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaXlucGtuYXNodHdzZWNoYmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTQyODQsImV4cCI6MjA2OTMzMDI4NH0.hMMIib0lh8NxeFLU3FpOyGzKHJg82bUZAXGarY6qL5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});